name: lettutor_edu_clone
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  dio: ^4.0.6
  get: ^4.6.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  flutter_html: ^2.2.1
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.0.3
  video_player: ^2.4.7
  flutter_localizations:
    sdk: flutter
  sprintf: ^6.0.0
  validators: ^3.0.0
  image_picker: ^0.8.6
  google_sign_in: ^5.4.2
  flutter_login_facebook: ^1.7.0
  flutter_cached_pdfview: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen_runner: ^3.1.1
  build_runner: ^2.1.2
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_logo.png"

flutter_gen:
  output: lib/res/gen/
  line_length: 180
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  colors:
    inputs:
      - assets/colors/colors.xml
flutter:

  uses-material-design: true

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
  assets:
    - assets/
    - assets/fonts/
    - assets/svg/
    - assets/images/
    - assets/svg/login/
    - assets/svg/common/
    - assets/svg/app/
    - assets/svg/course/
    - assets/svg/schedule/
    - assets/svg/history/
